### ISSUE TITLE
"Server url must be Https"

### ISSUE THREAD

**Issue by abjinugu** [OctopusDeploy/OctoWatch#1]
why this restriction?

**Comment by thebigmoosey** [comment]
Hi @abjinugu, late last year, Apple announced a new security feature to iOS called App Transport Security (ATS) and they now require all apps to use secure network connections over trusted https.

We can use tools like [ngrok](https://ngrok.com) to setup a trusted secure tunnel in cases (like local networks) where we may not have trusted https, otherwise ATS will stop the requests, giving you this "Network Error". If an external tunnel is not an option, you may be out of luck unfortunately.

Sorry we can't be of more help in this case, but we're operating within the confines of Apple and their ATS rules for native apps.

**Comment by matt-richardson** [comment]
Octopus 3.15 now supports integration with Let's Encrypt, so you can easily setup an SSL cert.

**Comment by thebigmoosey** [comment]
Closing issue

**Comment by abjinugu** [comment]
Makes sense.. thanks for the update
